# Generated by Django 4.2.6 on 2023-12-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_customer_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_review',
            field=models.BooleanField(default=True),
        ),
    ]
