# Generated by Django 4.2.6 on 2024-01-05 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentextraction',
            name='amount_per_sample',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tubeextraction',
            name='amount_per_sample',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
