# Generated by Django 4.2.6 on 2023-12-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='dna_protocol',
        ),
        migrations.RemoveField(
            model_name='process',
            name='rna_protocol',
        ),
        migrations.AddField(
            model_name='process',
            name='pcr_dna_protocol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pcr_dna', to='pcr.thermalcyclerprotocol'),
        ),
        migrations.AddField(
            model_name='process',
            name='pcr_rna_protocol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pcr_rna', to='pcr.thermalcyclerprotocol'),
        ),
        migrations.AddField(
            model_name='process',
            name='qpcr_dna_protocol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qpcr_dna', to='pcr.thermalcyclerprotocol'),
        ),
        migrations.AddField(
            model_name='process',
            name='qpcr_rna_protocol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qpcr_rna', to='pcr.thermalcyclerprotocol'),
        ),
    ]
