# Generated by Django 4.2.6 on 2023-11-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='controls',
            field=models.ManyToManyField(through='pcr.ControlOrder', to='pcr.control'),
        ),
        migrations.AddField(
            model_name='assay',
            name='reagents',
            field=models.ManyToManyField(through='pcr.ReagentOrder', to='pcr.reagent'),
        ),
    ]
