# Generated by Django 4.2.6 on 2023-12-27 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('instruction', models.TextField()),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcr.extractionprotocol')),
                ('reagents', models.ManyToManyField(to='pcr.reagentextraction')),
                ('tubes', models.ManyToManyField(to='pcr.tubeextraction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('protocol', 'number'), name='step_unique', violation_error_message='A step number for this extraction protocol already exists.'),
        ),
    ]
