# Generated by Django 4.2.6 on 2023-11-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sample',
            name='batch_sample_id_unique',
        ),
    ]
