# Generated by Django 4.2.6 on 2023-11-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='date_performed',
        ),
        migrations.RemoveField(
            model_name='process',
            name='date_performed',
        ),
    ]
