# Generated by Django 4.2.6 on 2023-12-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0002_step_step_step_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='reagents',
        ),
        migrations.RemoveField(
            model_name='step',
            name='tubes',
        ),
    ]
