# Generated by Django 4.2.6 on 2023-11-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0002_remove_batch_date_performed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='assay_name',
        ),
    ]
