# Generated by Django 4.2.6 on 2023-11-05 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0002_alter_assay_user_alter_assaylist_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='control',
            name='control_unique',
        ),
    ]
