# Generated by Django 4.2.6 on 2023-12-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0002_alter_thermalcyclerprotocol_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermalcyclerprotocol',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='thermalcyclerprotocol',
            name='type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA')], default='DNA', max_length=25),
        ),
    ]
