# Generated by Django 4.2.6 on 2023-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0002_remove_sample_batch_sample_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionprotocol',
            name='doc_url',
            field=models.URLField(blank=True),
        ),
    ]
