# Generated by Django 4.2.6 on 2024-01-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0002_alter_reagentextraction_amount_per_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionprotocol',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
