# Generated by Django 4.2.6 on 2023-12-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0003_remove_step_reagents_remove_step_tubes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='instruction',
            field=models.CharField(max_length=500),
        ),
    ]
