# Generated by Django 4.2.6 on 2023-12-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0003_remove_batch_number_of_samples_batch_is_extracted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plate',
            constraint=models.UniqueConstraint(fields=('user', 'lot_number', 'catalog_number'), name='plate_lot_cat_unique', violation_error_message='Plates with the same catalog number and lot already exists.'),
        ),
        migrations.AddConstraint(
            model_name='reagent',
            constraint=models.UniqueConstraint(fields=('user', 'lot_number', 'catalog_number'), name='reagent_lot_cat_unique', violation_error_message='A reagent with the same catalog number and lot already exists.'),
        ),
        migrations.AddConstraint(
            model_name='tube',
            constraint=models.UniqueConstraint(fields=('user', 'lot_number', 'catalog_number'), name='tube_lot_cat_unique', violation_error_message='Tubes with the same catalog number and lot already exists.'),
        ),
    ]
