# Generated by Django 4.2.6 on 2024-01-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0003_gel'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='gel',
            field=models.ManyToManyField(to='pcr.gel'),
        ),
        migrations.RemoveField(
            model_name='process',
            name='plate',
        ),
        migrations.AddField(
            model_name='process',
            name='plate',
            field=models.ManyToManyField(to='pcr.plate'),
        ),
    ]
