# Generated by Django 4.2.6 on 2024-01-09 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0003_alter_extractionprotocol_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='min_samples',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
