# Generated by Django 4.2.6 on 2023-12-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0003_alter_thermalcyclerprotocol_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='date_processed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='dna_protocol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dna_protocol', to='pcr.thermalcyclerprotocol'),
        ),
        migrations.AlterField(
            model_name='process',
            name='plate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pcr.plate'),
        ),
        migrations.AlterField(
            model_name='process',
            name='rna_protocol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rna_protocol', to='pcr.thermalcyclerprotocol'),
        ),
    ]
