# Generated by Django 4.2.6 on 2023-11-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0003_remove_control_control_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reagentorder',
            name='user',
        ),
    ]
