# Generated by Django 4.2.6 on 2023-12-20 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0004_plate_plate_lot_cat_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plate',
            name='plate_lot_cat_unique',
        ),
        migrations.RemoveConstraint(
            model_name='reagent',
            name='reagent_lot_cat_unique',
        ),
        migrations.RemoveConstraint(
            model_name='tube',
            name='tube_lot_cat_unique',
        ),
    ]
