# Generated by Django 4.2.6 on 2023-11-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0004_alter_sample_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcr.batch'),
        ),
    ]
