# Generated by Django 4.2.6 on 2024-01-04 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0004_process_gel_remove_process_plate_process_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='volume',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
