# Generated by Django 4.2.6 on 2023-12-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0004_alter_step_instruction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='step',
            name='step_unique',
        ),
    ]
