# Generated by Django 4.2.6 on 2024-01-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0005_remove_gel_wells_gel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gel',
            name='size',
            field=models.IntegerField(choices=[(12, '12'), (24, '24'), (48, '48')], default=24),
        ),
    ]
