# Generated by Django 4.2.6 on 2023-12-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0005_remove_step_step_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
