# Generated by Django 4.2.6 on 2023-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0005_remove_plate_plate_lot_cat_unique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='date_created',
        ),
        migrations.AddField(
            model_name='process',
            name='date_processed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thermalcyclerprotocol',
            name='type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA')], default='DNA', max_length=25),
        ),
    ]
