# Generated by Django 4.2.6 on 2023-11-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0006_alter_reagent_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='size',
            field=models.IntegerField(choices=[(8, '8'), (24, '24'), (48, '48'), (96, '96'), (384, '384')], default=96),
        ),
    ]
