# Generated by Django 4.2.6 on 2024-01-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0006_alter_gel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='gel_per_assay',
            field=models.BooleanField(default=True),
        ),
    ]
