# Generated by Django 4.2.6 on 2023-11-23 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0007_alter_plate_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='stock_concentration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='unit_concentration',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'NOT_APPLICABLE'), ('MOLES', 'M'), ('MILLIMOLES', 'mM'), ('MICROMOLES', 'µM'), ('NANOMOLES', 'nM'), ('UNITS', 'U/µL'), ('X', 'X')], default='MILLIMOLES', max_length=25),
        ),
    ]
