# Generated by Django 4.2.6 on 2024-01-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0008_alter_plate_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='size',
            field=models.IntegerField(choices=[(8, '8'), (24, '24'), (48, '48'), (96, '96'), (384, '384')], default=96),
        ),
    ]
