# Generated by Django 4.2.6 on 2023-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0008_alter_reagent_stock_concentration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='location',
            field=models.ManyToManyField(to='pcr.location'),
        ),
    ]
