# Generated by Django 4.2.6 on 2024-01-10 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0009_alter_plate_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='min_samples',
            new_name='min_samples_per_gel',
        ),
        migrations.RemoveField(
            model_name='process',
            name='gel_per_assay',
        ),
        migrations.AddField(
            model_name='process',
            name='min_samples_per_plate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
