# Generated by Django 4.2.6 on 2023-11-25 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcr', '0009_control_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flourescence',
            new_name='Fluorescence',
        ),
    ]
