# Generated by Django 4.2.6 on 2023-11-28 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0011_control_exp_date_plate_exp_date_reagent_exp_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='is_pcr_water',
        ),
        migrations.AlterField(
            model_name='reagent',
            name='stock_concentration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='unit_concentration',
            field=models.CharField(blank=True, choices=[('MOLES', 'M'), ('MILLIMOLES', 'mM'), ('MICROMOLES', 'µM'), ('NANOMOLES', 'nM'), ('UNITS', 'U/µL'), ('X', 'X')], default='MILLIMOLES', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='unit_volume',
            field=models.CharField(choices=[('L', 'L'), ('mL', 'mL'), ('µL', 'µL')], default='µL', max_length=25),
        ),
    ]
