# Generated by Django 4.2.6 on 2024-01-11 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0012_assay_ladder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='min_samples_per_gel',
            new_name='min_samples_per_gel_dna',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='min_samples_per_plate',
            new_name='min_samples_per_plate_dna',
        ),
        migrations.AddField(
            model_name='process',
            name='min_samples_per_gel_rna',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='process',
            name='min_samples_per_plate_rna',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
