# Generated by Django 4.2.6 on 2024-01-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0013_rename_min_samples_per_gel_process_min_samples_per_gel_dna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='pcr_dna_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='pcr_rna_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='qpcr_dna_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='qpcr_rna_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
