# Generated by Django 4.2.6 on 2023-11-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0014_assay_is_pcr_water_assay_is_polymerase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='is_pcr_water',
        ),
        migrations.RemoveField(
            model_name='assay',
            name='is_polymerase',
        ),
        migrations.AddField(
            model_name='reagent',
            name='is_pcr_water',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=25),
        ),
        migrations.AddField(
            model_name='reagent',
            name='is_polymerase',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=25),
        ),
    ]
