# Generated by Django 4.2.6 on 2023-11-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0015_remove_assay_is_pcr_water_remove_assay_is_polymerase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='is_pcr_water',
        ),
        migrations.RemoveField(
            model_name='reagent',
            name='is_polymerase',
        ),
        migrations.AddField(
            model_name='reagent',
            name='pcr_reagent',
            field=models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('POLYMERASE', 'POLYMERASE'), ('WATER', 'WATER')], default=None, max_length=25, null=True),
        ),
    ]
