# Generated by Django 4.2.6 on 2024-01-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0015_process_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='batches',
            field=models.ManyToManyField(to='pcr.batch'),
        ),
    ]
