# Generated by Django 4.2.6 on 2023-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0016_remove_reagent_is_pcr_water_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='is_negative_ctrl',
            field=models.BooleanField(default=False),
        ),
    ]
