# Generated by Django 4.2.6 on 2024-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0017_alter_process_date_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='date_processed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
