# Generated by Django 4.2.6 on 2023-11-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0017_control_is_negative_ctrl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentassay',
            name='final_concentration_unit',
            field=models.CharField(blank=True, choices=[('MOLES', 'M'), ('MILLIMOLES', 'mM'), ('MICROMOLES', 'µM'), ('NANOMOLES', 'nM'), ('UNITS', 'U/µL'), ('X', 'X')], default=None, max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(fields=('user', 'lot_number'), name='control_unique', violation_error_message='Control with this lot number already exists.'),
        ),
    ]
