# Generated by Django 4.2.6 on 2023-11-30 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0018_alter_reagentassay_final_concentration_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentassay',
            name='final_concentration',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
