# Generated by Django 4.2.6 on 2024-01-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0018_alter_process_date_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='plates',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
