# Generated by Django 4.2.6 on 2023-12-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0019_alter_reagentassay_final_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
