# Generated by Django 4.2.6 on 2023-12-05 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0020_alter_reagent_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assay',
            name='assay_unique',
        ),
        migrations.AlterField(
            model_name='assay',
            name='method',
            field=models.CharField(choices=[('qPCR', 'qPCR'), ('PCR', 'PCR')], default='PCR', max_length=25),
        ),
        migrations.AlterField(
            model_name='reagentextraction',
            name='amount_per_sample',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tubeextraction',
            name='amount_per_sample',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='assay',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'method'), name='assay_unique', violation_error_message='An assay with this name and method already exists.'),
        ),
    ]
