# Generated by Django 4.2.6 on 2024-01-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0023_assay_dye_volume_per_well_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='type',
            field=models.CharField(choices=[('qPCR', 'qPCR'), ('PCR', 'PCR')], default='PCR', max_length=25),
        ),
    ]
