# Generated by Django 4.2.6 on 2024-01-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0024_alter_plate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='type',
            field=models.CharField(choices=[('PCR', 'PCR'), ('qPCR', 'qPCR')], default='PCR', max_length=25),
        ),
    ]
