# Generated by Django 4.2.6 on 2024-01-25 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0025_alter_plate_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='min_samples_per_plate_dna',
            new_name='min_samples_per_plate_dna_qpcr',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='min_samples_per_plate_rna',
            new_name='min_samples_per_plate_rna_qpcr',
        ),
        migrations.AddField(
            model_name='process',
            name='min_samples_per_plate_dna_pcr',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='process',
            name='min_samples_per_plate_rna_pcr',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
