# Generated by Django 4.2.6 on 2024-01-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0026_rename_min_samples_per_plate_dna_process_min_samples_per_plate_dna_qpcr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='plate',
        ),
        migrations.AddField(
            model_name='process',
            name='pcr_plate',
            field=models.ManyToManyField(related_name='pcr_plate', to='pcr.plate'),
        ),
        migrations.AddField(
            model_name='process',
            name='qpcr_plate',
            field=models.ManyToManyField(related_name='qpcr_plate', to='pcr.plate'),
        ),
    ]
