# Generated by Django 4.2.6 on 2024-01-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0027_remove_process_plate_process_pcr_plate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='min_samples_per_gel_dna',
            new_name='min_samples_per_gel',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='plates',
            new_name='plates_for_qpcr',
        ),
        migrations.RemoveField(
            model_name='process',
            name='min_samples_per_gel_rna',
        ),
        migrations.AddField(
            model_name='process',
            name='pcr_gels_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='plates_for_pcr',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
