# Generated by Django 4.2.6 on 2024-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0028_rename_min_samples_per_gel_dna_process_min_samples_per_gel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='dye_in_ladder',
            field=models.BooleanField(default=False),
        ),
    ]
