# Generated by Django 4.2.6 on 2024-01-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0030_process_is_plus_one_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='sequence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assay',
            name='dye_in_ladder',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='pcr_reagent',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('POLYMERASE', 'Polymerase'), ('WATER', 'Water')], default=None, max_length=25, null=True),
        ),
    ]
