# Generated by Django 4.2.6 on 2024-01-29 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0032_alter_reagent_pcr_reagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='multiplicates',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
