# Generated by Django 4.2.6 on 2024-02-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0036_alter_batch_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='dye_in_ladder',
            field=models.BooleanField(default=False),
        ),
    ]
