# Generated by Django 4.2.6 on 2024-02-18 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0037_alter_assay_dye_in_ladder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
