# Generated by Django 4.2.6 on 2024-02-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0038_alter_reagent_volume'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assay',
            name='assay_unique',
        ),
        migrations.RemoveConstraint(
            model_name='assaycode',
            name='assay_code_unique',
        ),
        migrations.RemoveConstraint(
            model_name='batch',
            name='batch_unique',
        ),
        migrations.RemoveConstraint(
            model_name='control',
            name='control_unique',
        ),
        migrations.RemoveConstraint(
            model_name='extractionprotocol',
            name='extraction_protocol_unique',
        ),
        migrations.RemoveConstraint(
            model_name='fluorescence',
            name='flourescence_unique',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='location_unique',
        ),
        migrations.RemoveConstraint(
            model_name='sample',
            name='user_lab_id_unique',
        ),
        migrations.RemoveConstraint(
            model_name='thermalcyclerprotocol',
            name='thermal_cycler_protocol_unique',
        ),
        migrations.AlterField(
            model_name='extractionprotocol',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
