# Generated by Django 4.2.6 on 2024-02-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0039_remove_assay_assay_unique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='is_negative_ctrl',
        ),
    ]
