# Generated by Django 4.2.6 on 2024-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0040_remove_control_is_negative_ctrl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentassay',
            name='final_concentration_unit',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('mM', 'mM'), ('µM', 'µM'), ('nM', 'nM'), ('U/µL', 'U/µL'), ('X', 'X')], default=None, max_length=25, null=True),
        ),
    ]
