# Generated by Django 4.2.6 on 2024-02-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0044_batch_negative_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='control_usage',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='reagent_usage',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
