# Generated by Django 4.2.6 on 2024-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0045_process_control_usage_process_reagent_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assaycode',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='control',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='control',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dye',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dye',
            name='catalog_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dye',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dye',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='extractionprotocol',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fluorescence',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gel',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gel',
            name='catalog_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gel',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ladder',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ladder',
            name='catalog_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ladder',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ladder',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plate',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plate',
            name='catalog_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plate',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='catalog_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='forward_sequence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='reverse_sequence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab_id_num',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tube',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tube',
            name='catalog_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tube',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tube',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
