# Generated by Django 4.2.6 on 2024-04-14 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0047_process_loading_method_dna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dye',
            name='threshold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='gel',
            name='threshold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ladder',
            name='threshold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plate',
            name='threshold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reagent',
            name='threshold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reagent',
            name='threshold_unit',
            field=models.CharField(choices=[('L', 'L'), ('mL', 'mL'), ('µL', 'µL')], default='µL', max_length=25),
        ),
        migrations.AddField(
            model_name='tube',
            name='threshold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
