# Generated by Django 4.2.6 on 2024-04-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0049_dye_threshold_diff_gel_threshold_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dye',
            name='merged_catalog_numbers',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='gel',
            name='merged_catalog_numbers',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='ladder',
            name='merged_catalog_numbers',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='plate',
            name='merged_catalog_numbers',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='reagent',
            name='merged_catalog_numbers',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='tube',
            name='merged_catalog_numbers',
            field=models.JSONField(default=[]),
        ),
    ]
