# Generated by Django 4.2.6 on 2024-04-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0050_dye_merged_catalog_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dye',
            name='merged_catalog_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gel',
            name='merged_catalog_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='ladder',
            name='merged_catalog_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='plate',
            name='merged_catalog_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='merged_catalog_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='tube',
            name='merged_catalog_numbers',
            field=models.JSONField(default=list),
        ),
    ]
