# Generated by Django 4.2.6 on 2024-04-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0051_alter_dye_merged_catalog_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
