# Generated by Django 4.2.6 on 2024-04-26 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0052_control_brand_control_catalog_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='control',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
