# Generated by Django 4.2.6 on 2024-04-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0053_control_date_created_control_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dye',
            old_name='merged_catalog_numbers',
            new_name='merged_lot_numbers',
        ),
        migrations.RenameField(
            model_name='gel',
            old_name='merged_catalog_numbers',
            new_name='merged_lot_numbers',
        ),
        migrations.RenameField(
            model_name='ladder',
            old_name='merged_catalog_numbers',
            new_name='merged_lot_numbers',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='merged_catalog_numbers',
            new_name='merged_lot_numbers',
        ),
        migrations.RenameField(
            model_name='reagent',
            old_name='merged_catalog_numbers',
            new_name='merged_lot_numbers',
        ),
        migrations.RenameField(
            model_name='tube',
            old_name='merged_catalog_numbers',
            new_name='merged_lot_numbers',
        ),
    ]
