# Generated by Django 4.2.6 on 2024-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0054_rename_merged_catalog_numbers_dye_merged_lot_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='merged_lot_numbers',
            field=models.JSONField(default=list),
        ),
    ]
