# Generated by Django 4.2.6 on 2024-04-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0055_control_merged_lot_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ladders'),
        ),
    ]
