# Generated by Django 4.2.6 on 2024-05-05 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0057_reagent_mixture_volume_per_reaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='threshold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='control',
            name='threshold_diff',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
