# Generated by Django 4.2.6 on 2024-05-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0059_sample_unique_sample'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sample',
            name='unique_sample',
        ),
    ]
