# Generated by Django 4.2.6 on 2024-05-08 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcr', '0060_remove_sample_unique_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='mixture_volume_per_reaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
