# Generated by Django 4.2.6 on 2023-12-12 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeplate',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storeplate',
            name='name',
            field=models.CharField(default='PLATE', max_length=25),
        ),
        migrations.AlterField(
            model_name='storereagent',
            name='name',
            field=models.CharField(default='REAGENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='storereagent',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storetube',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storetube',
            name='name',
            field=models.CharField(default='TUBE', max_length=25),
        ),
    ]
