# Generated by Django 4.2.6 on 2023-12-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.brand'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='affiliate_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
