# Generated by Django 4.2.6 on 2023-12-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_contact_brand_alter_kit_affiliate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
