# Generated by Django 4.2.6 on 2023-12-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_kit_order_kits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_added',
        ),
        migrations.AddField(
            model_name='order',
            name='date_processed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
