# Generated by Django 4.2.6 on 2023-12-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_date_added_order_date_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
