# Generated by Django 4.2.6 on 2023-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_orders_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitorder',
            name='in_inventory',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
