# Generated by Django 4.2.6 on 2023-12-20 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_kitorder_in_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitorder',
            name='in_inventory',
        ),
        migrations.AddField(
            model_name='kitorder',
            name='remaining_transfers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
