# Generated by Django 4.2.6 on 2023-12-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_kitorder_in_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kits'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orders_file',
            field=models.FileField(blank=True, null=True, upload_to='orders'),
        ),
    ]
