# Generated by Django 4.2.6 on 2023-12-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_brand_logo_alter_kit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='default-brand.jpg', null=True, upload_to='brands'),
        ),
    ]
