# Generated by Django 4.2.6 on 2023-12-22 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='flags',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
