# Generated by Django 4.2.6 on 2023-12-22 21:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_review_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='flags',
        ),
        migrations.AddField(
            model_name='review',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
