# Generated by Django 4.2.6 on 2023-12-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_review_flags_review_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='description',
            field=models.TextField(default='Kit Description'),
        ),
    ]
