# Generated by Django 4.2.6 on 2023-12-31 23:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_kit_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PLATE', max_length=25)),
                ('wells', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.kit')),
            ],
        ),
    ]
