# Generated by Django 4.2.6 on 2024-01-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_storegel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storegel',
            name='name',
            field=models.CharField(default='GEL', max_length=25),
        ),
    ]
