# Generated by Django 4.2.6 on 2024-03-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_storeplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/brands'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, default='kits/default-kit.png', null=True, upload_to='main/static/kits'),
        ),
    ]
