# Generated by Django 4.2.6 on 2024-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_kit_kit_unique_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='catalog_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AddConstraint(
            model_name='kit',
            constraint=models.UniqueConstraint(fields=('brand', 'catalog_number'), name='kit_unique', violation_error_message='A kit with the same brand and catalog number already exists.'),
        ),
    ]
