# Generated by Django 4.2.6 on 2024-04-24 12:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_kit_catalog_number_kit_kit_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storegel',
            name='wells',
        ),
        migrations.AddField(
            model_name='storegel',
            name='size',
            field=models.IntegerField(choices=[(12, '12'), (24, '24'), (48, '48')], default=24),
        ),
        migrations.AlterField(
            model_name='storereagent',
            name='pcr_reagent',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('PRIMER', 'Primer'), ('POLYMERASE', 'Polymerase'), ('WATER', 'Water')], default=None, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='StoreLadder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GEL', max_length=25)),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.kit')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GEL', max_length=25)),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.kit')),
            ],
        ),
        migrations.CreateModel(
            name='StoreAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ACCESSORY', max_length=25)),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.kit')),
            ],
        ),
    ]
