# Generated by Django 4.2.6 on 2024-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_storegel_wells_storegel_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='storeaccessory',
            name='name',
            field=models.CharField(default='ACCESSORY', max_length=100),
        ),
        migrations.AlterField(
            model_name='storedye',
            name='name',
            field=models.CharField(default='GEL', max_length=100),
        ),
        migrations.AlterField(
            model_name='storegel',
            name='name',
            field=models.CharField(default='GEL', max_length=100),
        ),
        migrations.AlterField(
            model_name='storeladder',
            name='name',
            field=models.CharField(default='GEL', max_length=100),
        ),
        migrations.AlterField(
            model_name='storeplate',
            name='name',
            field=models.CharField(default='PLATE', max_length=100),
        ),
        migrations.AlterField(
            model_name='storereagent',
            name='name',
            field=models.CharField(default='REAGENT', max_length=100),
        ),
        migrations.AlterField(
            model_name='storetube',
            name='name',
            field=models.CharField(default='TUBE', max_length=100),
        ),
    ]
