# Generated by Django 4.2.6 on 2024-04-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_kit_name_alter_storeaccessory_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreAccessory',
        ),
    ]
