# Generated by Django 4.2.6 on 2024-04-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_delete_storeaccessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedye',
            name='name',
            field=models.CharField(default='DYE', max_length=100),
        ),
        migrations.AlterField(
            model_name='storeladder',
            name='name',
            field=models.CharField(default='LADDER', max_length=100),
        ),
    ]
