# Generated by Django 4.2.6 on 2024-04-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_storedye_name_alter_storeladder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereagent',
            name='forward_sequence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storereagent',
            name='reverse_sequence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
