# Generated by Django 4.2.6 on 2024-05-05 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_storecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereagent',
            name='mixture_volume_per_reaction',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storereagent',
            name='pcr_reagent',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('PRIMER', 'Primer'), ('POLYMERASE', 'Polymerase'), ('MIXTURE', 'Mixture'), ('WATER', 'Water')], default=None, max_length=25, null=True),
        ),
    ]
