# Generated by Django 4.2.6 on 2024-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_storereagent_mixture_volume_per_reaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='media/brands/default-brand.png', null=True, upload_to='brands'),
        ),
    ]
