# Generated by Django 4.2.6 on 2024-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, default='kits/default-kit.png', null=True, upload_to='kits'),
        ),
    ]
