# Generated by Django 4.2.6 on 2024-05-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_storereagent_mixture_volume_per_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
