# Generated by Django 4.2.6 on 2024-02-11 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logins', models.BigIntegerField(default=0)),
                ('date', models.DateField(default=datetime.date(2024, 2, 11), editable=False)),
            ],
        ),
    ]
