# This files keeps all enums as limits to how many object can be created per user. Premium tier will be unlimited!

class LIMITS:
  # DEPENDANT LIMITS
  ASSAY_LIMIT = 10
  ASSAY_CODE_LIMIT = 20
  BATCH_LIMIT = 500
  PROCESS_LIMIT = 500

  # INDEPENDANT LIMITS
  SAMPLES_PER_BATCH_LIMIT = 100
  EXTRACTION_PROTOCOL_LIMIT = 20
  LOCATION_LIMIT = 50
  LADDER_LIMIT = 50
  DYE_LIMIT = 50
  PLATE_LIMIT = 50
  GEL_LIMIT = 50
  TUBE_LIMIT = 50
  REAGENT_LIMIT = 150
  THERMAL_CYCLER_PROTOCOL_LIMIT = 50

  
